version: '3.8'

services:
  url-shortener:
    build: .
    container_name: url-shortener
    image: url-shortener:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
