version: '3.8'

services:
  url-shortener:
    build: .
    container_name: url-shortener
    image: url-shortener:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/url
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
    networks:
      - app-network
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:15
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=master
      - POSTGRESQL_PASSWORD=master
      - POSTGRESQL_DATABASE=url
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - app-network

volumes:
  postgresql_data:
    driver: local

networks:
  app-network:
    driver: bridge
